export const BookActionTypes = {
  BOOKS_FETCH_START: "BOOKS_FETCH_START",
  BOOKS_FETCH_SUCCESS: "BOOKS_FETCH_SUCCESS",
  BOOKS_FETCH_ERROR: "BOOKS_FETCH_ERROR",

  BOOK_FETCH_START: "BOOK_FETCH_START",
  BOOK_FETCH_SUCCESS: "BOOK_FETCH_SUCCESS",
  BOOK_FETCH_ERROR: "BOOK_FETCH_ERROR",

  BOOK_CREATE_START: "BOOK_CREATE_START",
  BOOK_CREATE_SUCCESS: "BOOK_CREATE_SUCCESS",
  BOOK_CREATE_ERROR: "BOOK_CREATE_ERROR",
  CLEAR_BOOK_CREATE_SUCCESS: "CLEAR_BOOK_CREATE_SUCCESS",

  BOOK_UPDATE_START: "BOOK_UPDATE_START",
  BOOK_UPDATE_SUCCESS: "BOOK_UPDATE_SUCCESS",
  BOOK_UPDATE_ERROR: "BOOK_UPDATE_ERROR",
};
